[tools]
node = "24"

"npm:typescript" = "latest"
"npm:typescript-language-server" = "latest"
"npm:@google/clasp" = "latest"
"npm:@devcontainers/cli" = "latest"
"npm:graphql-language-service-cli" = "latest"

[settings]
experimental = true
